fusion:
  d_model: 256
  nhead: 8
  num_decoder_layers: 3
  dim_feedforward: 1024
  dropout: 0.1
  activation: 'relu'
  normalize_before: False
  return_intermediate_dec: False
  pos_embed_len: 1
  upper_face3d_indices: [6, 8, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63]
  lower_face3d_indices: [0,1,2,3,4,5,7,9,10,11,12,13,14]
  dynamic_K: 8
  dynamic_ratio: 4
  output_dim: 64

video_encoder:
  block_expansion: 24
  num_channels: 3
  max_features: 256
  num_blocks: 4
  # 改变这个可以改变图片的输入尺寸
  scale_factor: 0.5


audio_encoder:
  num_encoder_layers: 8
  feature_dim: 256
  nhead: 8
  feedforward_dim: 512
  seq_len: 28


# loss函数的
#比较唇部区域用的
mouth_weight: 4
# 直接比较3DMM用的
exp_weight: 1
# 唇形同步器用的
sync_weight: 1
# 重构权重
rec_weight: 2
# render_loss用的
rec_low_weight: [1,0]
# 唇形同步器
# sync_net_pre_train: "checkpoint/syncNet/epoch_18_metrices_0.6473926901817322.pth"
landmark_dim: 40
audio_dim: 1024


audio_win_size: 5
render_win_size: 13
# 面部遮罩大小
mask_width: 100
mask_height: 60
device_id: [1]
checkpoint_dir: "checkpoint/exp3DMM"
result_dir: "result/exp3DMM"
epoch: 10000
lr: 0.0001
# 在lr_scheduler_step后改变学习率
lr_scheduler_step: [2,5]

exp_3dmm_pre_train: "checkpoint/exp3DMM/驱动视频变版本/epoch_9_metrices_0.9193817776367068.pth"
render_pre_train: "checkpoint/render/edit_epoch_23_metrices_0.9345089584052061.pth"
