fusion:
  d_model: 256
  nhead: 8
  num_decoder_layers: 3
  dim_feedforward: 1024
  dropout: 0.1
  activation: 'relu'
  normalize_before: False
  return_intermediate_dec: False
  pos_embed_len: 1
  upper_face3d_indices: [6, 8, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63]
  lower_face3d_indices: [0,1,2,3,4,5,7,9,10,11,12,13,14]
  dynamic_K: 8
  dynamic_ratio: 4
  output_dim: 64

video_encoder:
  d_model: 256
  nhead: 8
  num_encoder_layers: 3
  dim_feedforward: 1024
  dropout: 0.1
  activation: "relu"
  normalize_before: False
  pos_embed_len: 256
  input_dim: 64
  aggregate_method: "self_attention_pooling"

# loss函数的
mouth_weight: [5,5]
exp_weight: [2,2]
# rec_weight中，第一项是L1 loss，第二项是ssim
rec_low_weight: [0.1,0.9]
triple_weight: 1
rec_weight: 3
triple_dis: 5

audio_win_size: 5
render_win_size: 13
device_id: [0]
checkpoint_dir: "checkpoint/exp3DMM"
result_dir: "result/exp3DMM"
epoch: 1
lr: 0.0001
# 在lr_scheduler_step后改变学习率
lr_scheduler_step: 1000000

# exp_3dmm_pre_train: "checkpoint/exp3DMM/epoch_7_loss_11.65384018048644.pth"
render_pre_train: "checkpoint/render/warp_epoch_0_loss_551.1777420043945.pth"