mapping_net: 
  coeff_nc: 73
  descriptor_nc: 256
  layer: 3

warpping_net: 
  base_nc: 32
  decoder_layer: 3
  encoder_layer: 5

editing_net:
  base_nc: 64
  # test，原来值为3
  layer: 3
  num_res_blocks: 2

common:
  descriptor_nc: 256
  image_nc: 3
  max_nc: 256
  use_spect: False

# loss函数用的
# rec_weight中，第一项是L1 loss，第二项是ssim
rec_low_weight: [60,0]
vgg_weight: [1,1,1,1,1]
num_scales: 4
resize_mode: "bilinear"


# 训练用的
device_id: [1]
# epoch
epoch: 1000000
# 在epoch的前warp_epoch中，会先不训练edit，然后会共同训练
warp_epoch: 10
lr: 0.0001
# 在lr_scheduler_step后改变学习率
lr_scheduler_step: [20]
# render_win_size需要不小于12
render_win_size: 13

# 相关文件夹
render_pre_train: "checkpoint/render/warp_epoch_2_metrices_0.7443441254932032.pth"
# dis_pre_train: "checkpoint/render/epoch_54_metrices_0.7367087345975758_dis.pth"
checkpoint_dir: "checkpoint/render"
result_dir: "result/render"

