fusion:
  d_model: 256
  nhead: 8
  num_decoder_layers: 3
  dim_feedforward: 1024
  dropout: 0.1
  activation: 'relu'
  normalize_before: False
  return_intermediate_dec: False
  pos_embed_len: 1
  upper_face3d_indices: [6, 8, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63]
  lower_face3d_indices: [0,1,2,3,4,5,7,9,10,11,12,13,14]
  dynamic_K: 8
  dynamic_ratio: 4
  output_dim: 64

video_encoder:
  block_expansion: 32
  num_channels: 3
  max_features: 1024
  num_blocks: 5
  # 改变这个可以改变图片的输入尺寸
  scale_factor: 1


mapping_net: 
  coeff_nc: 73
  descriptor_nc: 256
  layer: 3

warpping_net: 
  base_nc: 32
  decoder_layer: 3
  encoder_layer: 5

editing_net:
  base_nc: 64
  layer: 3
  num_res_blocks: 2

common:
  descriptor_nc: 256
  image_nc: 3
  max_nc: 256
  use_spect: False

common_weight: [0.1,0.9]
vgg_weight: [0.2,0.2,0.2,0.2,0.2]
# win_size需要不小于12
win_size: 12

device_id: [0]
checkpoint_dir: "checkpoint/render"
result_dir: "result/render"
epoch: 100
lr: 0.001
lr_scheduler_step: 0

exp_3dmm_pre_train: "checkpoint/exp3DMM/epoch_7_loss_11.65384018048644.pth"
# render_pre_train: "checkpoint/render/epoch_5_loss_16.151315189898014.pth"

