landmark_dim: 40
audio_dim: 1024

# 训练参数
epoch: 100000
lr_scheduler_step: [13,26]
device_id: [0]
lr: 0.0005



# 相关文件夹
sync_net_pre_train: "checkpoint/syncNet/epoch_120_metrices_0.7664950489997864.pth"
checkpoint_dir: "checkpoint/syncNet"
