D_input: single
VGGFace_pretrain_path: ''
aspect_ratio: 1.0
audio_nc: 256
augment_target: false
batchSize: 16
beta1: 0.5
beta2: 0.999
checkpoints_dir: ./checkpoints
clip_len: 1
crop: false
crop_len: 16
crop_size: 256
data_path: /home/SENSETIME/zhouhang1/Downloads/VoxCeleb2/voxceleb2_train.csv
dataset_mode: voxtest
defined_driven: false
dis_feat_rec: false
display_winsize: 224
driven_type: face
driving_pose: true
feature_encoded_dim: 2560
feature_fusion: concat
filename_tmpl: '{:06}.jpg'
fitting_iterations: 10
frame_interval: 1
frame_rate: 25
gan_mode: hinge
gen_video: true
generate_from_audio_only: true
generate_interval: 1
gpu_ids: '0'
has_mask: false
heatmap_size: 3
hop_size: 160
how_many: .inf
init_type: xavier
init_variance: 0.02
input_id_feature: true
input_path: ./checkpoints/results/input_path
isTrain: false
label_mask: false
lambda_D: 1
lambda_contrastive: 100
lambda_crossmodal: 1
lambda_feat: 10.0
lambda_image: 1.0
lambda_rotate_D: 0.1
lambda_softmax: 1000000
lambda_vgg: 10.0
lambda_vggface: 5.0
landmark_align: false
landmark_type: min
list_end: .inf
list_num: 0
list_start: 0
load_from_opt_file: false
load_landmark: false
lr: 0.001
lrw_data_path: /home/SENSETIME/zhouhang1/Downloads/VoxCeleb2/voxceleb2_train.csv
max_dataset_size: 9223372036854775807
meta_path_vox: ./misc/demo.csv
mode: cpu
model: av
multi_gpu: false
nThreads: 1
n_mel_T: 4
name: demo
ndf: 64
nef: 16
netA: resseaudio
netA_sync: ressesync
netD: multiscale
netE: fan
netG: modulate
netV: resnext
ngf: 64
no_TTUR: false
no_flip: true
no_ganFeat_loss: false
no_gaussian_landmark: false
no_id_loss: false
no_instance: false
no_pairing_check: false
no_spectrogram: false
no_vgg_loss: false
noise_pose: true
norm_A: spectralinstance
norm_D: spectralinstance
norm_E: spectralinstance
norm_G: spectralinstance
num_bins_per_frame: 4
num_classes: 5830
num_clips: 1
num_frames_per_clip: 5
num_inputs: 1
onnx: false
optimizer: adam
output_nc: 3
phase: test
pose_dim: 12
positional_encode: false
preprocess_mode: resize_and_crop
results_dir: ./results/
save_path: ./results/
serial_batches: false
start_ind: 0
style_dim: 2560
style_feature_loss: true
target_crop_len: 0
train_dis_pose: false
train_recognition: false
train_sync: false
train_word: false
trainer: audio
use_audio: 1
use_audio_id: 0
use_transformer: false
verbose: false
vgg_face: false
which_epoch: latest
word_loss: false
